import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins({
 
  weight: ["100", "200", "400", "500","600","800"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title:  {
    default: "Tech Gear",
    template: "%s | Tech Gear" ,
  },
  description: " Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased`}
      >
        <header>
           <Navbar></Navbar>
        </header>
        {children}
        <footer>
           <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
